Repository CodeDead/Advanced-PortChecker, pull requests merged in 2025-04, with the labels that each got.

#48 feat: Dependency upgrades, Yarn upgrade
  .yarn/releases/yarn-4.8.1.cjs
  .yarn/releases/yarn-4.9.1.cjs
  .yarnrc.yml
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  yarn.lock
Labels: dependencies

#49 Feature/upgrades
  .eslintignore
  .eslintrc.json
  .github/workflows/release.yml
  .github/workflows/test.yml
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/gen/schemas/acl-manifests.json
  src-tauri/gen/schemas/desktop-schema.json
  src-tauri/gen/schemas/linux-schema.json
  src-tauri/tauri.conf.json
  src/components/AlertDialog/index.jsx
  src/components/App/index.jsx
  src/components/GridList/index.jsx
  src/components/Layout/index.jsx
  src/components/LoadingBar/index.jsx
  src/components/PortInput/index.jsx
  src/components/Theme/index.jsx
  src/components/TopBar/index.jsx
  src/components/UpdateDialog/index.jsx
  src/contexts/MainContextProvider/index.jsx
  src/main.css
  src/main.jsx
  src/reducers/MainReducer/Actions/index.js
  src/routes/About/index.jsx
  src/routes/Home/index.jsx
  src/routes/Settings/index.jsx
  src/utils/Updater/index.js
  vite.config.js
  yarn.lock
Labels: enhancement, dependencies

#50 Feature/update api
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/components/Layout/index.jsx
  src/routes/Settings/index.jsx
  src/utils/Updater/index.js
  yarn.lock
Labels: enhancement, dependencies

#51 Feature/update api
  src-tauri/src/main.rs
Labels: bug

#52 Create ja_jp.json
  src/languages/ja_jp.json
Labels: translation

#53 Feature/ja jp
  README.md
  src-tauri/Cargo.lock
  src/contexts/MainContextProvider/index.jsx
  src/languages/ja_jp.json
  src/routes/Settings/index.jsx
  yarn.lock
Labels: enhancement, translation, dependencies

#54 feat: dependency upgrades
  package.json
  src-tauri/Cargo.lock
  yarn.lock
Labels: dependencies
